# Generated by Django 5.0.4 on 2024-05-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
