# Generated by Django 5.0.4 on 2024-05-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_roomimage_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
