# Generated by Django 5.0.4 on 2024-05-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_read',
            new_name='is_read_admin',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read_cleint',
            field=models.BooleanField(default=False),
        ),
    ]
