# Generated by Django 5.0.4 on 2024-05-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date_occupied',
            new_name='day_occupied',
        ),
    ]
