# Generated by Django 5.0.4 on 2024-05-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_date_occupied_booking_day_occupied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='day_occupied',
            new_name='days_occupied',
        ),
    ]
