# Generated by Django 5.0.4 on 2024-05-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_day_occupied_booking_days_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('occupied', 'Occupied'), ('checked_out', 'Checked Out')], default='confirmed', max_length=20),
        ),
    ]
