# Generated by Django 5.0.4 on 2024-05-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('checked_in', 'Checked in'), ('checked_out', 'Checked Out')], default='pending', max_length=20),
        ),
    ]
